In [1]:
import pandas as pd
import requests, json, os

id = 'usnavy09'
apikey = 'J0RL197TS3DBGG61VRPDAF8AECQXM7AU07DVZS8NY553P'
url = 'http://www.recycling-info.or.kr/sds/JsonApi.do?'
items = []

pid = 'NTN028'
year = 2020

param = f'PID={pid}&YEAR={year}&USRID={id}&KEY={apikey}'

try:
    response = requests.get(url=url + param).json()
    # 예외처리
    if 'error' in response:
        raise Exception(f"API 오류: {response['error']}")
    elif response['result'][0]['ERR_CODE'] != 'E000':
        raise Exception(f"error : {response['result'][0]['RESULT']}")
    
    # 집계된 데이터 제외
    for item in response['data']:
        if '합계' not in item.values() and '소계' not in item.values():
            items.append(item)
    item
    
    # 컬럼을 한글로 바꾼 후 데이터 저장
    year_label = response['result'][0]['YEAR']
    title_label = response['result'][0]['TITLE']
    df = pd.json_normalize(items)
    df.rename(columns=response['dataHeader'][0], inplace=True)
    
    # data-files 폴더 생성
    ''' 
    if 'data-files' not in os.listdir():
        os.makedirs('data-files')
    df.to_csv(f'data-files/{year_label}_{title_label}.csv', index=False)
    print(f"데이터 저장완료 : {year_label}_{title_label}.csv")
    '''
except requests.exceptions.RequestException as e:
    print(f"네트워크 오류: {e}")
    
except Exception as e:
    print(f"예외 발생: {e}")

네트워크 오류: Expecting value: line 5 column 1 (char 4)

In [20]:
df

,지방비_(지자체 시군구)_자체예산,지방비_(광역시도)_자체예산,지방채,기타,구분_시군구,YYYY년 세입수수료_(지자체 시군구),총계,지방비_(지자체 시군구)_시도지원예산,국비,차관,구분_시도,지방비_소계
0,0,146865196,0,0,서울,0,147583696,0,718500,0,서울,146865196
1,37048337,0,0,0,종로구,10147000,48012584,817247,0,0,서울,37865584
2,24384289,0,0,0,중구,15675000,40059289,0,0,0,서울,24384289
3,34066369,0,0,0,용산구,7482000,41968769,397400,23000,0,서울,34463769
4,29787818,0,0,0,성동구,9034000,38821818,0,0,0,서울,29787818
...,...,...,...,...,...,...,...,...,...,...,...,...
240,6605710,0,0,0,화천군,368000,8706110,713400,1019000,0,강원,7319110
241,2819434,0,0,0,양구군,652000,3654492,183058,0,0,강원,3002492
242,4038011,0,0,0,인제군,696000,4734011,0,0,0,강원,4038011
243,1970588,0,0,0,고성군,879000,3788207,70584,868035,0,강원,2041172
244,4525437,0,0,0,양양군,1063000,6038188,443160,6591,0,강원,4968597