In [9]:
import pandas as pd

In [10]:
# 데이터 불러오기
# <=2018 : NTN011, 2019 = ,NTN011  2020 = NTN011
h_16 = pd.read_csv('data-files/2016_4가(생활폐기물관리인원및장비현황).csv')
h_17 = pd.read_csv('data-files/2017_4가(생활폐기물관리인원및장비현황).csv')
h_18 = pd.read_csv('data-files/2018_4가(생활폐기물관리인원및장비현황).csv')
h_19 = pd.read_csv('data-files/2019_다-2-a. (시군구) 관리인원 및 장비현황.csv')
h_20 = pd.read_csv('data-files/2020_3-나-1). (시군구) 관리인원 및 장비현황.csv')

print(h_18.columns)
print(h_19.columns)
print(h_20.columns)

Index(['자치단체_인원(명)', '자치단체_차량(대)', '자가처리_중장비(대)', '처리업체_중장비(대)', '자치단체_손수레(대)',
       '구분_시군구', '처리업체_인원(명)', '총계_중장비(대)', '자가처리_손수레(대)', '총계_인원(명)',
       '처리업체_차량(대)', '자치단체_중장비(대)', '자가처리_인원(명)', '처리업체_손수레(대)', '자가처리_차량(대)',
       '총계_차량(대)', '총계_손수레(대)', '구분_시도'],
      dtype='object')
Index(['시도', '시군구', '총계_인원(명)', '총계_차량(대)', '총계_손수레(대)', '총계_중장비(대)',
       '공공처리_인원(명)', '공공처리_차량(대)', '공공처리_손수레(대)', '공공처리_중장비(대)', '자가처리_인원(명)',
       '자가처리_차량(대)', '자가처리_손수레(대)', '자가처리_중장비(대)', '위탁처리_인원(명)', '위탁처리_차량(대)',
       '위탁처리_손수레(대)', '위탁처리_중장비(대)'],
      dtype='object')
Index(['시도', '시군구', '총계_인원(명)', '총계_차량(대)', '총계_손수레(대)', '총계_중장비(대)',
       '공공처리_인원(명)', '공공처리_차량(대)', '공공처리_손수레(대)', '공공처리_중장비(대)', '자가처리_인원(명)',
       '자가처리_차량(대)', '자가처리_손수레(대)', '자가처리_중장비(대)', '위탁처리_인원(명)', '위탁처리_차량(대)',
       '위탁처리_손수레(대)', '위탁처리_중장비(대)'],
      dtype='object')

In [21]:
def NTN011_preprocessing_before_2019(data,year):
    cols_inc_tot = [c for c in data.columns if '총계' in c]
    data = data.drop(columns=cols_inc_tot)
    data = data.rename(columns={'구분_시도' : '시도', '구분_시군구' : '시군구'})

    data = pd.melt(data, id_vars=['시도','시군구'])
    data['소속기관'], data['인원장비'] = zip(*data['variable'].apply(lambda x: x.split('_')))
    data = data.drop(columns='variable')
    data = data.rename(columns={'value' : '관리인원or장비_대수'})
    data = data[['시도','시군구','소속기관','인원장비','관리인원or장비_대수']]
    data['year'] = year
    return data

df_18 = NTN011_preprocessing_before_2019(h_18, 2018)
df_17 = NTN011_preprocessing_before_2019(h_17, 2017)
df_16 = NTN011_preprocessing_before_2019(h_16, 2016)

In [22]:
def NTN011_preprocessing_after_2019(data, year):
    cols_inc_tot = [c for c in data.columns if '총계' in c]
    data = data.drop(columns=cols_inc_tot)

    data = pd.melt(data, id_vars=['시도','시군구'])
    data['소속기관'], data['인원장비'] = zip(*data['variable'].apply(lambda x: x.split('_')))
    data = data.drop(columns='variable')
    data = data.rename(columns={'value' : '관리인원or장비_대수'})
    data = data[['시도','시군구','소속기관','인원장비','관리인원or장비_대수']]
    data['year'] = year
    return data

df_19 = NTN011_preprocessing_after_2019(h_19, 2019)
df_20 = NTN011_preprocessing_after_2019(h_20, 2020)

In [23]:
a = pd.DataFrame()
a = pd.concat([df_16, df_17, df_18, df_19, df_20], ignore_index=True)
a.to_csv('data/2016_2020_관리인원_장비현황.csv', index=False)

In [14]:
# 생활폐기물 예산 및 집행내역
# 2018 = NTN028, NTN029 2019 = NTN015, NTN016 2020 = NTN015, NTN016

In [83]:
bgt_2018 = pd.read_csv('data-files/2018_9가(생활폐기물관리예산).csv')
t2 = pd.read_csv('data-files/2018_9나(생활폐기물관리예산 집행내역).csv')
bgt_2019 = pd.read_csv('data-files/2019_라-2-a. (시군구) 생활폐기물관리예산.csv')
t22 = pd.read_csv('data-files/2019_라-2-b. (시군구) 생활폐기물관리예산집행내역.csv')
bgt_2020 = pd.read_csv('data-files/2020_4-나-1). (시군구) 생활폐기물관리예산.csv')
t1.columns,t11.columns

(Index(['지방비_(지자체 시군구)_자체예산', '지방비_(광역시도)_자체예산', '지방채', '기타', '구분_시군구',
        'YYYY년 세입수수료_(지자체 시군구)', '총계', '지방비_(지자체 시군구)_시도지원예산', '국비', '차관',
        '구분_시도', '지방비_소계'],
       dtype='object'),
 Index(['시도', '시군구', '총계', '국비', '지 방 비_소계', '지 방 비_(광역시도에서만 작성)_자체 예산',
        '지 방 비_(지자체 시군구에서만 작성)_시도지원예산', '지 방 비_(지자체 시군구에서만 작성)_자체예산', '차관',
        '지방채', '2019년 세입 수수료_(광역도시에서만 작성)', '기타'],
       dtype='object'))

In [86]:
t11.head()

,시도,시군구,총계,국비,지 방 비_소계,지 방 비_(광역시도에서만 작성)_자체 예산,지 방 비_(지자체 시군구에서만 작성)_시도지원예산,지 방 비_(지자체 시군구에서만 작성)_자체예산,차관,지방채,2019년 세입 수수료_(광역도시에서만 작성),기타
0,서울,서울시,148373040,3183000,145190040,145190040,0,0,0,0,0,0
1,서울,종로구,34416437,0,23096437,0,571630,22524807,0,0,11320000,0
2,서울,중구,39347153,0,23669153,0,0,23669153,0,0,15678000,0
3,서울,용산구,44504817,141500,36501317,0,489425,36011892,0,0,7862000,0
4,서울,성동구,47651045,50000,37205045,0,268154,36936891,0,0,10396000,0

In [93]:
data = t11.rename(columns=lambda x:x.replace(' ', ''))
data

,시도,시군구,총계,국비,지방비_소계,지방비_(광역시도에서만작성)_자체예산,지방비_(지자체시군구에서만작성)_시도지원예산,지방비_(지자체시군구에서만작성)_자체예산,차관,지방채,2019년세입수수료_(광역도시에서만작성),기타
0,서울,서울시,148373040,3183000,145190040,145190040,0,0,0,0,0,0
1,서울,종로구,34416437,0,23096437,0,571630,22524807,0,0,11320000,0
2,서울,중구,39347153,0,23669153,0,0,23669153,0,0,15678000,0
3,서울,용산구,44504817,141500,36501317,0,489425,36011892,0,0,7862000,0
4,서울,성동구,47651045,50000,37205045,0,268154,36936891,0,0,10396000,0
...,...,...,...,...,...,...,...,...,...,...,...,...
241,강원,화천군,8529034,1183187,6950847,0,727935,6222912,0,0,395000,0
242,강원,양구군,5875665,16000,5196665,0,5430,5191235,0,0,663000,0
243,강원,인제군,12983146,0,11690146,0,0,11690146,0,0,1293000,0
244,강원,고성군,5914568,1886000,3012568,0,1330200,1682368,0,0,1016000,0
245,강원,양양군,11852622,2496800,7989822,0,2990380,4999442,0,0,1366000,0

In [114]:
# 관리예산 전처리
def NTN028_preprocessing_before_2019(data, year):
    data = data.drop(columns=['총계','지방비_소계'])

    data = pd.melt(data,['구분_시도', '구분_시군구', '지방채', '기타', '국비', '차관', 'YYYY년 세입수수료_(지자체 시군구)'])
    data = data.rename(columns={'구분_시도' : '시도'
                    , '구분_시군구' : '시군구'
                    , 'YYYY년 세입수수료_(지자체 시군구)' : '세입수수료'
                    , 'variable' : '지방비_분류'
                    , 'value' : '지방비'
                    })
    data['지방비_분류'] = data['지방비_분류'].str.split('_').str[-1]
    return data

test = NTN028_preprocessing_before_2019(t1, 2018)

     시도  시군구  지방채  기타       국비  차관     세입수수료  지방비_분류       지방비
0    서울   서울    0   0   718500   0         0    자체예산         0
1    서울  종로구    0   0        0   0  10147000    자체예산  37048337
2    서울   중구    0   0        0   0  15675000    자체예산  24384289
3    서울  용산구    0   0    23000   0   7482000    자체예산  34066369
4    서울  성동구    0   0        0   0   9034000    자체예산  29787818
..   ..  ...  ...  ..      ...  ..       ...     ...       ...
730  강원  화천군    0   0  1019000   0    368000  시도지원예산    713400
731  강원  양구군    0   0        0   0    652000  시도지원예산    183058
732  강원  인제군    0   0        0   0    696000  시도지원예산         0
733  강원  고성군    0   0   868035   0    879000  시도지원예산     70584
734  강원  양양군    0   0     6591   0   1063000  시도지원예산    443160

[735 rows x 9 columns]

In [109]:
def NTN015_preprocessing_after_2019(data, year):
    data = data.rename(columns=lambda x:x.replace(' ', ''))
    data = data.drop(columns=['총계','지방비_소계'])

    data = pd.melt(data,['시도', '시군구', '지방채', '기타', '국비', '차관', '2019년세입수수료_(광역도시에서만작성)'])
    data = data.rename(columns={
                    '2019년세입수수료_(광역도시에서만작성)' : '세입수수료'
                    , 'variable' : '지방비_분류'
                    , 'value' : '지방비'
                    })
    data['지방비_분류'] = data['지방비_분류'].str.split('_').str[-1]
    return data

t_2019 = NTN015_preprocessing_after_2019(t11, 2019)

In [76]:
df[df['구분_시군구']=='종로구']

,구분_시도,구분_시군구,지방채,기타,국비,차관,YYYY년 세입수수료_(지자체 시군구),variable,value
1,서울,종로구,0,0,0,0,10147000,지방비_(지자체 시군구)_자체예산,37048337
246,서울,종로구,0,0,0,0,10147000,지방비_(광역시도)_자체예산,0
491,서울,종로구,0,0,0,0,10147000,지방비_(지자체 시군구)_시도지원예산,817247

In [56]:
df['variable'].value_counts()

지방비_(지자체 시군구)_자체예산      245
지방비_(광역시도)_자체예산         245
총계                      245
지방비_(지자체 시군구)_시도지원예산    245
지방비_소계                  245
Name: variable, dtype: int64

In [52]:
df['variable'].value_counts()

지방비_(지자체 시군구)_자체예산      245
지방비_(광역시도)_자체예산         245
지방비_(지자체 시군구)_시도지원예산    245
Name: variable, dtype: int64

In [32]:
t11[t11['2019년 세입 수수료_(광역도시에서만 작성)'] == 0]

,시도,시군구,총계,국비,지 방 비_소계,지 방 비_(광역시도에서만 작성)_자체 예산,지 방 비_(지자체 시군구에서만 작성)_시도지원예산,지 방 비_(지자체 시군구에서만 작성)_자체예산,차관,지방채,2019년 세입 수수료_(광역도시에서만 작성),기타
0,서울,서울시,148373040,3183000,145190040,145190040,0,0,0,0,0,0
64,인천,경제청,0,0,0,0,0,0,0,0,0,0
84,경기,경기도,0,0,0,0,0,0,0,0,0,0
116,충북,충북도,0,0,0,0,0,0,0,0,0,0
128,충남,충남도,0,0,0,0,0,0,0,0,0,0
144,전북,전북도,0,0,0,0,0,0,0,0,0,0
159,전남,전남도,0,0,0,0,0,0,0,0,0,0
182,경북,경북도,0,0,0,0,0,0,0,0,0,0
205,경남,경남도,0,0,0,0,0,0,0,0,0,0
227,강원,강원도,0,0,0,0,0,0,0,0,0,0

In [18]:
t1[t1['구분_시도'] == '서울'].head()

,지방비_(지자체 시군구)_자체예산,지방비_(광역시도)_자체예산,지방채,기타,구분_시군구,YYYY년 세입수수료_(지자체 시군구),총계,지방비_(지자체 시군구)_시도지원예산,국비,차관,구분_시도,지방비_소계
0,0,146865196,0,0,서울,0,147583696,0,718500,0,서울,146865196
1,37048337,0,0,0,종로구,10147000,48012584,817247,0,0,서울,37865584
2,24384289,0,0,0,중구,15675000,40059289,0,0,0,서울,24384289
3,34066369,0,0,0,용산구,7482000,41968769,397400,23000,0,서울,34463769
4,29787818,0,0,0,성동구,9034000,38821818,0,0,0,서울,29787818

In [19]:
t1[t1['지방채']>0]

,지방비_(지자체 시군구)_자체예산,지방비_(광역시도)_자체예산,지방채,기타,구분_시군구,YYYY년 세입수수료_(지자체 시군구),총계,지방비_(지자체 시군구)_시도지원예산,국비,차관,구분_시도,지방비_소계
26,0,49286272,8300000,0,부산,17684562,77782634,0,2511800,0,부산,49286272
131,30471768,0,3000000,0,아산시,5397000,41154268,469000,1816500,0,충남,30940768
182,51503300,0,5000000,0,포항시,12041000,70451000,1345700,561000,0,경북,52849000

In [20]:
t2.head()

,시설설치비_기타시설,수집운반등처리비_시설관리 운영비,구분_시군구,시설설치비_소계,총계,수집운반등처리비_장비구입비,수집운반등처리비_인건비,수집운반등처리비_기타,시설설치비_매립시설,수집운반등처리비_차량운영비,수집운반등처리비_위탁처리비,구분_시도,수집운반등처리비_소계
0,3096211,87631177,서울,3096211,151247457,0,0,60520069,0,0,0,서울,148151246
1,0,209668,종로구,0,17078652,0,9608205,0,0,140779,7120000,서울,17078652
2,0,0,중구,0,20653599,0,11115402,0,0,0,9538197,서울,20653599
3,0,191812,용산구,0,22175700,1084609,6212617,388038,0,2247,14296377,서울,22175700
4,0,3292000,성동구,0,30903580,316000,10655000,627400,0,591990,15421190,서울,30903580